"use client";

import Link from "next/link";
import { CalendarClock, CheckSquare2, FileText, HeartHandshake, Mail, MessageSquareText, Phone, ShieldAlert } from "lucide-react";
import type { DashboardData, Person } from "@/lib/domain";
import { formatDate, relativeDate } from "@/lib/utils";
import { Avatar } from "@/components/ui/avatar";
import { HealthBadge, StageBadge } from "@/components/ui/badge";

export function PersonSummary({ person, data, compact = false, showOpen = true }: { person: Person; data: DashboardData; compact?: boolean; showOpen?: boolean }) {
  const tasks = data.tasks.filter((task) => task.personId === person.id && task.status === "open");
  const activities = data.activities.filter((activity) => activity.personId === person.id);
  return <article className={compact ? "" : "surface overflow-hidden"}>
    <header className={compact ? "pb-6" : "border-b border-border bg-paper p-6 lg:p-8"}><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><Avatar initials={person.initials} name={person.name} size="lg" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="display text-3xl font-medium">{person.name}</h2><StageBadge stage={person.stage} /></div><p className="mt-1 text-sm text-muted">{person.organization ?? person.email ?? "Private relationship"}</p><div className="mt-3 flex flex-wrap gap-2"><HealthBadge health={person.health} /><span className="inline-flex items-center gap-1.5 rounded-full bg-ink/5 px-2.5 py-1 text-xs font-semibold"><ShieldAlert className="size-3.5" />{person.priority === "high" ? "High priority" : "Normal priority"}</span></div></div>{showOpen && <Link href={`/people/${person.id}`} className="inline-flex min-h-10 items-center justify-center rounded-lg border border-border bg-paper px-4 text-sm font-semibold">Open full workspace</Link>}</div></header>
    <div className={compact ? "grid gap-6" : "grid gap-0 lg:grid-cols-[minmax(0,1fr)_280px]"}><div className={compact ? "space-y-6" : "space-y-7 p-6 lg:p-8"}>
      <section aria-labelledby={`next-${person.id}`}><p className="eyebrow">Next action</p><h3 id={`next-${person.id}`} className="mt-2 text-lg font-semibold">{person.nextAction ? `${person.nextAction.type[0].toUpperCase()}${person.nextAction.type.slice(1)} · ${formatDate(person.nextAction.dueAt, true)}` : "No next action scheduled"}</h3>{!person.nextAction && ["follow-up", "pending-signup"].includes(person.stage) ? <p className="mt-2 flex items-center gap-2 text-sm font-semibold text-danger"><CalendarClock className="size-4" />Required before this record is complete</p> : <p className="mt-2 text-sm text-muted">{person.nextAction ? relativeDate(person.nextAction.dueAt) : "Review the relationship before scheduling contact."}</p>}</section>
      <section><p className="eyebrow">Relationship health</p><p className="mt-2 text-sm leading-6">{person.healthExplanation}</p>{person.risks.map((risk) => <p key={risk} className="mt-3 flex items-start gap-2 rounded-lg bg-danger/7 p-3 text-sm text-danger"><ShieldAlert className="mt-0.5 size-4 shrink-0" />{risk}</p>)}</section>
      <section><div className="mb-3 flex items-center justify-between"><p className="eyebrow">Recent history</p><span className="text-xs text-muted">{activities.length} {activities.length === 1 ? "entry" : "entries"}</span></div>{activities.length ? <ol className="space-y-3">{activities.slice(0, 4).map((activity) => <li key={activity.id} className="grid grid-cols-[28px_1fr] gap-3"><span className="mt-0.5 flex size-7 items-center justify-center rounded-full bg-ink/5"><MessageSquareText className="size-3.5" aria-hidden /></span><div><p className="text-sm leading-5">{activity.summary}</p><time className="text-xs text-muted" dateTime={activity.at}>{formatDate(activity.at, true)}</time></div></li>)}</ol> : <p className="text-sm text-muted">No activity has been recorded.</p>}</section>
    </div><aside className={compact ? "space-y-5" : "space-y-5 border-t border-border bg-ivory/60 p-6 lg:border-l lg:border-t-0"}><section><p className="eyebrow">Contact</p><div className="mt-3 space-y-2 text-sm">{person.email && <a className="flex items-center gap-2 hover:underline" href={`mailto:${person.email}`}><Mail className="size-4 text-muted" />{person.email}</a>}{person.phone && <a className="flex items-center gap-2 hover:underline" href={`tel:${person.phone}`}><Phone className="size-4 text-muted" />{person.phone}</a>}</div></section><section><p className="eyebrow">Open commitments</p><ul className="mt-3 space-y-3">{tasks.length ? tasks.map((task) => <li key={task.id} className="text-sm"><span className="flex items-start gap-2 font-medium"><CheckSquare2 className="mt-0.5 size-4 shrink-0 text-gold-strong" />{task.title}</span><span className="ml-6 text-xs text-muted">Due {formatDate(task.dueAt)}</span></li>) : <li className="text-sm text-muted">No open commitments.</li>}</ul></section><section><p className="eyebrow">Context</p><div className="mt-3 flex flex-wrap gap-2">{person.tags.map((tag) => <span key={tag} className="rounded-full border border-border bg-paper px-2.5 py-1 text-xs">{tag}</span>)}</div></section><section><p className="eyebrow">Files</p><p className="mt-3 flex items-center gap-2 text-sm text-muted"><FileText className="size-4" />No files attached</p></section>{person.consentNote && <section><p className="eyebrow">Consent</p><p className="mt-2 flex gap-2 text-sm leading-5"><HeartHandshake className="mt-0.5 size-4 shrink-0 text-success" />{person.consentNote}</p></section>}</aside></div>
  </article>;
}
