"use client";

import Link from "next/link";
import { AlertTriangle, ArrowRight, CalendarClock, CheckCircle2, Clock3, HeartHandshake, Network, ShieldAlert } from "lucide-react";
import { useDashboard } from "@/hooks/use-dashboard";
import { DataBoundary } from "@/components/data-boundary";
import { EmptyState } from "@/components/empty-state";
import { PageHeader } from "@/components/page-header";
import { Avatar } from "@/components/ui/avatar";
import { StageBadge } from "@/components/ui/badge";
import { relativeDate } from "@/lib/utils";
import type { QueueItem } from "@/lib/domain";
import { dashboardMetrics } from "@/lib/dashboard-metrics";

const iconFor: Record<QueueItem["category"], React.ComponentType<{ className?: string }>> = { "overdue-follow-up": Clock3, "due-today": CalendarClock, "onboarding-blocker": AlertTriangle, "overdue-commitment": CheckCircle2, relationship: HeartHandshake, review: CalendarClock, stalled: Clock3, "missing-action": AlertTriangle, risk: ShieldAlert, referral: Network };

export function TodayPage() {
  const query = useDashboard(); const data = query.data; const metrics = data ? dashboardMetrics(data) : null;
  return <DataBoundary isLoading={query.isLoading} isFetching={query.isFetching} error={query.error} onRetry={() => query.refetch()} isEmpty={Boolean(data && data.queue.length === 0)} empty={<EmptyState title="You’re caught up" message="Today has no overdue follow-ups, blockers, commitments, referrals, or relationship reviews." />}>
    {data && metrics && <><PageHeader eyebrow={new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric" }).format(new Date())} title="The work that matters today." description="One prioritized queue across outreach, onboarding, commitments, referrals, and active relationships. Each item explains why it is here." actions={<><Link href="/outreach" className="inline-flex min-h-10 items-center rounded-lg border border-border bg-paper px-4 text-sm font-semibold">Open outreach</Link><Link href="/tasks" className="inline-flex min-h-10 items-center rounded-lg bg-ink px-4 text-sm font-semibold text-ivory">Review tasks</Link></>} />
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
        <section aria-labelledby="priority-heading"><div className="mb-3 flex items-center justify-between"><h2 id="priority-heading" className="text-sm font-bold uppercase tracking-[.14em]">Priority queue</h2><span className="text-sm text-muted">{data.queue.length} items</span></div><ol className="surface divide-y divide-border overflow-hidden">{data.queue.map((item, index) => { const person = data.people.find((candidate) => candidate.id === item.personId)!; const Icon = iconFor[item.category]; return <li key={item.id}><Link href={`/people/${person.id}`} className="group grid gap-4 p-4 transition-colors hover:bg-gold-pale/20 sm:grid-cols-[42px_minmax(0,1fr)_auto] sm:items-center sm:p-5"><div className="relative"><Avatar initials={person.initials} name={person.name} /><span className="absolute -right-1 -top-1 flex size-5 items-center justify-center rounded-full bg-ink text-[10px] font-bold text-ivory" aria-label={`Priority ${index + 1}`}>{index + 1}</span></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{person.name}</h3><StageBadge stage={person.stage} compact /></div><p className="mt-2 flex items-start gap-2 text-sm font-medium"><Icon className="mt-0.5 size-4 shrink-0 text-gold-strong" aria-hidden />{item.reason}</p><p className="mt-1 text-sm text-muted">{item.recommendedAction}</p></div><div className="flex items-center justify-between gap-4 pl-14 text-xs text-muted sm:block sm:pl-0 sm:text-right"><span className={item.category.includes("overdue") || item.category === "risk" || item.category === "missing-action" ? "font-semibold text-danger" : ""}>{relativeDate(item.date)}</span><ArrowRight className="size-4 transition-transform group-hover:translate-x-1 sm:ml-auto sm:mt-3" aria-hidden /></div></Link></li>; })}</ol></section>
        <aside className="space-y-5" aria-label="Today summary"><section className="surface overflow-hidden"><div className="bg-ink p-5 text-ivory"><p className="eyebrow !text-gold">Operating pulse</p><p className="display mt-2 text-3xl">{metrics.activeClients} active relationships</p><p className="mt-2 text-sm leading-5 text-white/65">{metrics.needsAttention ? `${metrics.needsAttention} relationship${metrics.needsAttention === 1 ? "" : "s"} need attention.` : "No active relationships currently need attention."}</p></div><dl className="divide-y divide-border p-5 text-sm"><div className="flex justify-between py-3"><dt className="text-muted">Next-action coverage</dt><dd className="font-semibold">{metrics.nextActionCoverage}%</dd></div><div className="flex justify-between py-3"><dt className="text-muted">Onboarding blockers</dt><dd className="font-semibold text-warning">{metrics.onboardingBlockers} open</dd></div><div className="flex justify-between py-3"><dt className="text-muted">Overdue commitments</dt><dd className="font-semibold text-danger">{metrics.overdueCommitments} open</dd></div></dl></section><section className="surface p-5"><p className="eyebrow">Next review</p>{metrics.nextReview ? <><h2 className="display mt-2 text-2xl">{metrics.nextReview.name}</h2><p className="mt-2 text-sm text-muted">Relationship review · {relativeDate(metrics.nextReview.reviewAt!)}</p><Link href={`/people/${metrics.nextReview.id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-gold-strong">Prepare context <ArrowRight className="size-4" /></Link></> : <p className="mt-2 text-sm text-muted">No upcoming client review is scheduled.</p>}</section></aside>
      </div></>}
  </DataBoundary>;
}
