"use client";

import { useDashboard } from "@/hooks/use-dashboard";
import { DataBoundary } from "@/components/data-boundary";
import { PageHeader } from "@/components/page-header";
import { ActivityChart } from "./activity-chart";
import { dashboardMetrics } from "@/lib/dashboard-metrics";

export function ReportsPage() { const query = useDashboard(); const metrics = query.data ? dashboardMetrics(query.data) : null; return <DataBoundary isLoading={query.isLoading} isFetching={query.isFetching} error={query.error} onRetry={() => query.refetch()} isEmpty={false} empty={null}>{query.data && metrics && <><PageHeader eyebrow="Reports" title="Evidence for the next decision." description="Activity, follow-up completion, referral contribution, relationship health, onboarding, and operational exceptions with accessible data fallbacks." /><div className="grid gap-6 xl:grid-cols-2"><section className="surface p-6"><p className="eyebrow">Activity</p><h2 className="display mb-5 mt-2 text-2xl">Recent trend</h2><ActivityChart data={query.data.trends} /></section><section className="surface p-6"><p className="eyebrow">Operating measures</p><h2 className="display mt-2 text-2xl">Current performance</h2><div className="mt-6 space-y-6"><Progress label="Next-action coverage" value={metrics.nextActionCoverage} target="Target 95%" /><Progress label="Follow-up completion" value={metrics.followUpCompletion} target="Target 90%" /><Progress label="Onboarding visibility" value={metrics.onboardingVisibility} target="Target 100%" /><Progress label="Active record freshness" value={metrics.activeFreshness} target="Target 90%" /></div></section><section className="surface p-6 xl:col-span-2"><p className="eyebrow">Health distribution</p><div className="mt-5 grid gap-5 sm:grid-cols-4"><Health value={String(metrics.health.strong)} label="Strong" detail="Contact within 14 days" /><Health value={String(metrics.health.stable)} label="Stable" detail="No overdue work" /><Health value={String(metrics.health.needsAttention)} label="Needs attention" detail="Review required" /><Health value={String(metrics.health.atRisk)} label="At risk" detail="Risk and overdue work" /></div></section></div></>}</DataBoundary>; }
function Progress({ label, value, target }: { label: string; value: number; target: string }) { return <div><div className="flex justify-between text-sm"><span className="font-semibold">{label}</span><span className="text-muted">{value}% · {target}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-ink/8"><div className="h-full rounded-full bg-gold-strong" style={{ width: `${value}%` }} /></div></div>; }
function Health({ value, label, detail }: { value: string; label: string; detail: string }) { return <div className="border-l-2 border-gold pl-4"><p className="display text-3xl">{value}</p><p className="mt-1 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted">{detail}</p></div>; }
