"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3, Network } from "lucide-react";
import { useDashboard } from "@/hooks/use-dashboard";
import { DataBoundary } from "@/components/data-boundary";
import { WorkflowForm, Field, inputClass, value } from "@/components/workflow-form";
import { PageHeader } from "@/components/page-header";
import { Avatar } from "@/components/ui/avatar";
import { formatDate } from "@/lib/utils";

export function ReferralsPage() {
  const query = useDashboard(); const referrals = query.data?.referrals ?? [];
  return <DataBoundary isLoading={query.isLoading} isFetching={query.isFetching} error={query.error} onRetry={() => query.refetch()} isEmpty={false} empty={null}>
    {query.data && <><PageHeader eyebrow="Referrals" title="Every introduction stays attributable." description="See the referrer, referred person, consent/source note, progress, and conversion without losing the relationship thread." /><details className="surface mb-6 p-5"><summary className="cursor-pointer font-semibold">Record referral</summary><WorkflowForm className="mt-4" label="Save referral" build={data => ({ type: "referral.create", personId: value(data,"personId"), referrerId: value(data,"referrerId"), sourceNote: value(data,"sourceNote") })}><div className="grid gap-4 sm:grid-cols-2">{["referrerId","personId"].map(field => <Field key={field} label={field === "referrerId" ? "Referred by" : "Referred person"}><select name={field} required className={inputClass}><option value="">Choose person</option>{query.data.people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>)}</div><Field label="Referral source and consent note"><textarea name="sourceNote" required className={inputClass} /></Field></WorkflowForm></details><div className="grid gap-5 md:grid-cols-3">{referrals.map((referral) => { const person = query.data.people.find((candidate) => candidate.id === referral.personId)!; const referrer = query.data.people.find((candidate) => candidate.id === referral.referrerId); if (!person || !referrer) return <article key={referral.id} className="surface p-5"><h2 className="font-semibold">Archived referral attribution</h2><p className="text-sm">{referral.sourceNote}</p><p className="text-xs text-muted">Referrer {referral.referrerId} · Person {referral.personId}</p></article>; const status = referral.status === "converted" ? { icon: CheckCircle2, label: "Converted", className: "text-success bg-success/10" } : referral.status === "contacted" ? { icon: ArrowRight, label: "Contacted", className: "text-info bg-info/10" } : { icon: Clock3, label: "Awaiting outreach", className: "text-warning bg-warning/10" }; return <article key={referral.id} className="surface p-5"><div className="flex items-start justify-between gap-3"><Avatar initials={person.initials} name={person.name} /><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${status.className}`}><status.icon className="size-3.5" />{status.label}</span></div><h2 className="display mt-4 text-2xl"><Link href={`/people/${person.id}`} className="hover:underline">{person.name}</Link></h2><p className="mt-1 text-xs text-muted">Introduced {formatDate(referral.at)}</p><div className="my-5 flex items-center gap-2 text-sm"><Network className="size-4 text-gold-strong" /><span>Referred by <Link href={`/people/${referrer.id}`} className="font-semibold hover:underline">{referrer.name}</Link></span></div><p className="rounded-lg bg-ink/[.035] p-3 text-sm leading-5 text-muted">{referral.sourceNote}</p></article>; })}</div></>}
  </DataBoundary>;
}
