"use client";

import { useState } from "react";
import Link from "next/link";
import { DndContext, KeyboardSensor, PointerSensor, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { sortableKeyboardCoordinates } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { GripVertical, List, PanelsTopLeft } from "lucide-react";
import { WorkflowForm, Field, inputClass, value } from "@/components/workflow-form";
import { useDashboard } from "@/hooks/use-dashboard";
import { DataBoundary } from "@/components/data-boundary";
import { EmptyState } from "@/components/empty-state";
import { PageHeader } from "@/components/page-header";
import { Avatar } from "@/components/ui/avatar";
import { StageBadge } from "@/components/ui/badge";
import { stageToAPI } from "@/lib/api/client";
import { stages, stageLabel, type Person, type Stage } from "@/lib/domain";
import { formatDate } from "@/lib/utils";

export function PipelinePage() {
  const query = useDashboard(); const [view, setView] = useState<"board" | "list">("board");
  const [move, setMove] = useState<{ person: Person; stage: Stage } | null>(null);
  const movingPerson = query.data?.people.find(p => p.id === move?.person.id);
  const mutation = { mutate: setMove };
  const sensors = useSensors(useSensor(PointerSensor), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  const onDragEnd = ({ active, over }: DragEndEvent) => { if (!over || active.data.current?.person.stage === over.id) return; mutation.mutate({ person: active.data.current?.person as Person, stage: over.id as Stage }); };
  return <DataBoundary isLoading={query.isLoading} isFetching={query.isFetching} error={query.error} onRetry={() => query.refetch()} isEmpty={Boolean(query.data && !query.data.people.length)} empty={<EmptyState title="Pipeline is empty" message="Create a person or import approved source data to begin." />}>
    {query.data && <><PageHeader eyebrow="Lifecycle" title="A clear path, without losing context." description="Move records through the lifecycle. Every change calls the lifecycle service; validation failures restore the prior stage." actions={<div className="inline-flex rounded-lg border border-border bg-paper p-1"><button onClick={() => setView("board")} aria-pressed={view === "board"} className={`rounded-md p-2 ${view === "board" ? "bg-ink text-ivory" : "text-muted"}`} aria-label="Board view"><PanelsTopLeft className="size-4" /></button><button onClick={() => setView("list")} aria-pressed={view === "list"} className={`rounded-md p-2 ${view === "list" ? "bg-ink text-ivory" : "text-muted"}`} aria-label="List view"><List className="size-4" /></button></div>} />{move && movingPerson && <section className="surface mb-6 p-5"><h2 className="display mb-4 text-xl">Move {movingPerson.name} to {stageLabel[move.stage]}</h2><WorkflowForm label="Confirm lifecycle change" onSaved={() => setMove(null)} build={data => ({ type: "lifecycle.transition", id: movingPerson.id, expectedRevision: movingPerson.revision ?? 0, stage: stageToAPI(move.stage), ...(move.stage === "follow-up" ? { nextAction: { type: value(data,"actionType") as "call" | "review" | "meeting" | "message" | "onboarding", dueAt: new Date(value(data,"dueAt")).toISOString() } } : {}), ...(value(data,"reason") ? { reason: value(data,"reason") } : {}) })}>
{move.stage === "follow-up" && <div className="grid gap-4 sm:grid-cols-2"><Field label="Next action"><select className={inputClass} name="actionType">{["call","message","meeting","review","onboarding"].map(type => <option key={type}>{type}</option>)}</select></Field><Field label="Next-action date"><input name="dueAt" type="datetime-local" required className={inputClass} /></Field></div>}
<Field label="Reason"><textarea name="reason" required={["paused","not-interested","closed"].includes(move.stage)} className={inputClass} /></Field><button type="button" className="text-sm underline" onClick={() => setMove(null)}>Cancel change</button></WorkflowForm></section>}{view === "list" ? <PipelineList people={query.data.people} onMove={(person, stage) => mutation.mutate({ person, stage })} /> : <DndContext sensors={sensors} onDragEnd={onDragEnd}><div className="scrollbar-none flex gap-4 overflow-x-auto pb-4" aria-label="Lifecycle board">{stages.map((stage) => <PipelineColumn key={stage} stage={stage} people={query.data.people.filter((person) => person.stage === stage)} onMove={(person, next) => mutation.mutate({ person, stage: next })} />)}</div></DndContext>}</>}
  </DataBoundary>;
}

function PipelineColumn({ stage, people, onMove }: { stage: Stage; people: Person[]; onMove: (person: Person, stage: Stage) => void }) {
  const { setNodeRef, isOver } = useDroppable({ id: stage }); return <section ref={setNodeRef} className={`w-[290px] shrink-0 rounded-xl border p-3 ${isOver ? "border-gold-strong bg-gold-pale/40" : "border-border bg-ink/[.025]"}`} aria-labelledby={`stage-${stage}`}><div className="mb-3 flex items-center justify-between px-1"><h2 id={`stage-${stage}`} className="text-sm font-semibold">{stageLabel[stage]}</h2><span className="rounded-full bg-ink/7 px-2 py-0.5 text-xs font-semibold">{people.length}</span></div><div className="space-y-3">{people.map((person) => <PipelineCard key={person.id} person={person} onMove={onMove} />)}{!people.length && <div className="rounded-lg border border-dashed border-border p-6 text-center text-xs text-muted">No records in this stage</div>}</div></section>;
}
function PipelineCard({ person, onMove }: { person: Person; onMove: (person: Person, stage: Stage) => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: person.id, data: { person } });
  return <article ref={setNodeRef} style={{ transform: CSS.Translate.toString(transform) }} className={`rounded-xl border border-border bg-paper p-4 shadow-sm ${isDragging ? "opacity-60" : ""}`}><div className="flex items-start gap-3"><Avatar initials={person.initials} name={person.name} size="sm" /><div className="min-w-0 flex-1"><Link href={`/people/${person.id}`} className="font-semibold hover:underline">{person.name}</Link><p className="mt-0.5 truncate text-xs text-muted">{person.organization ?? person.email}</p></div><button {...listeners} {...attributes} className="cursor-grab rounded p-1 text-muted hover:bg-ink/5" aria-label={`Drag ${person.name} to another stage`}><GripVertical className="size-4" /></button></div><div className="mt-4">{person.nextAction ? <p className="text-xs"><span className="font-semibold">{person.nextAction.type[0].toUpperCase() + person.nextAction.type.slice(1)}</span> · {formatDate(person.nextAction.dueAt)}</p> : ["follow-up", "pending-signup"].includes(person.stage) ? <p className="text-xs font-semibold text-danger">Next action missing — correct now</p> : <p className="text-xs text-muted">No next action scheduled</p>}</div><label className="mt-4 block text-[11px] font-semibold text-muted">Move without dragging<select value={person.stage} onChange={(event) => onMove(person, event.target.value as Stage)} className="mt-1 w-full rounded-md border border-border bg-white px-2 py-1.5 text-xs text-ink">{stages.map((stage) => <option key={stage} value={stage}>{stageLabel[stage]}</option>)}</select></label></article>;
}
function PipelineList({ people, onMove }: { people: Person[]; onMove: (person: Person, stage: Stage) => void }) { return <div className="surface overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><caption className="sr-only">Lifecycle pipeline records</caption><thead className="border-b border-border bg-ink/[.025] text-xs uppercase tracking-wider text-muted"><tr><th className="p-4">Person</th><th className="p-4">Stage</th><th className="p-4">Next action</th><th className="p-4">Priority</th><th className="p-4">Change stage</th></tr></thead><tbody className="divide-y divide-border">{people.map((person) => <tr key={person.id}><td className="p-4 font-semibold"><Link href={`/people/${person.id}`}>{person.name}</Link></td><td className="p-4"><StageBadge stage={person.stage} /></td><td className="p-4">{person.nextAction ? `${person.nextAction.type} · ${formatDate(person.nextAction.dueAt)}` : <span className="font-semibold text-danger">Missing</span>}</td><td className="p-4 capitalize">{person.priority}</td><td className="p-4"><select aria-label={`Change ${person.name} stage`} value={person.stage} onChange={(event) => onMove(person, event.target.value as Stage)} className="rounded-md border border-border bg-white px-2 py-1.5">{stages.map((stage) => <option key={stage} value={stage}>{stageLabel[stage]}</option>)}</select></td></tr>)}</tbody></table></div>; }
